
#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 1/28/2019
Section: A3_1_2_Part3
Task Description: Controlling 2 Motors
Pseudocode:
*/
//Start Right Motor
//Start Left Motor
//Wait 10 sec
//Stop Right Motor
//Stop Left Motor


task main()
{                                     //Program begins, insert code within curly braces
	setMotor(rightMotor, 50);         //Start Right Motor
	setMotor(leftMotor, 50);          //Start Left Motor
	wait(10);                           //Wait 10 sec
	stopMotor(rightMotor);           //Stop Right Motor
	stopMotor(leftMotor);             //Stop Left Motor

}
