#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Controlling LEDs
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 1/28/2019
Section:
3.1.2 PT 1

Task Description:


Pseudocode:
Turn led off for one sec.
turn it on for one sec.
Turn led off for one sec.
turn it on for one sec.
Turn led off for one sec.

*/

task main()
{                                     //Program begins, insert code within curly braces
	turnLEDOff(green);
	wait(1);
	turnLEDOn(green);
	wait(1);
	turnLEDOff(green);
	wait(1);
	turnLEDOn(green);
	wait(1);
	turnLEDOff(green);

}
