#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: 3.1.3 Basic Inputs Programming
Team Members:Sharanya, Aditya, Juliana, Michael
Date:2/11/19
Section:POE


Task Description:A3_1_3_Part1 : Bump Switch


Pseudocode:When bump switch is pressed, the right motor moves at a speed of 63 for 5 seconds, and then stops.

*/

task main()
{                                     //Program begins, insert code within curly braces

	untilBump(bumpSwitch);//bump switch is pressed
	startMotor(rightMotor, 63);//right motor rotates at speed of 63
	wait(5);//waits for 5 seconds
	stopMotor(rightMotor);//motor stops



}
