#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 1/28/2019
Section:
Task Description:
Pseudocode:
*/
//Turn on LED until potentiometer is greater than 2048
//turn off Led
//Start left motor
//wait 3.5 sec
//stop left motor

task main()
{
	turnLEDOn(green);
	untilPotentiometerGreaterThan(2048, potentiometer);
	turnLEDOff(green);
	startMotor(leftMotor, 60);
	wait(3.5);
	stopMotor(leftMotor);

}
