#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: 3.1.3 Basic Inputs Programming
Team Members:Sharanya, Aditya, Juliana, Michael
Date:2/11/19
Section:POE


Task Description:A3_1_3_Part1 : Bump Switch


Pseudocode:When bump switch is pressed, the right motor moves at a speed of 63 for 5 seconds, and then stops.

*/

task main()
{                                     //Program begins, insert code within curly braces

	untilBump(port2,10);//bump switch is pressed (right motor)
	untilBump(port3,10);//bump switch is pressed (left motor)
	startMotor(port2, 63);//right motor starts at half speed
	startMotor(port3,63);//left motor starts at half speed
	untilBump(2, 10);//bump switch is pressed
	startMotor(port2, -63);//Right motor starts in reverse, half speed
	startMotor(port3,-63);//Left motor starts in reverse, half speeed
	wait(3.5);//both motors move in reverse for 3.5 seconds
	stopMotor(port2);//right motor stops
	stopMotor(port3);//left motor stops






}
