#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Controlling one motor
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 1/28/2019
Section:
3.1.2 PT 2


Task Description:


Pseudocode:

*/

task main()
{
	startMotor(port2, 63); //Starts motor that is reversed via motor and sensor setup at speed 63
	startMotor(port3, -63); //Starts motor at speed -63
	wait(5); // Waits 5 seconds
	stopMotor(port2); // Stops motor at port 2
	stopMotor(port3); // Stops motor at port 3

}
