#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Controlling a servomotor
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 2/11/2019
Section:


Task Description:


Pseudocode:
Program the servo to go to position -127 for 2 seconds.
Go to position 0 for 2 seconds.
Go to position 127 for 2 seconds.

*/

task main()
{
	setServo(servoMotor, -127); //Program the servo to go to position -127 for 2 seconds
	wait(2);
	setServo(servoMotor, -63); //Go to position -63 for 3 seconds.
	wait(3);
	setServo(servoMotor, 0); //Go to position 0 for 2 seconds.
	wait(2);
	setServo(servoMotor, 63); //Go position 63 for 3 seconds.
	wait(3);
	setServo(servoMotor, 127); //Go to position 127 for 2 seconds
	wait(2);

}
