#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members: Aditya, Sharanya, Juliana, Micheal
Date: 1/28/2019
Section:


Task Description:


Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	startMotor(port2, 50);
	startMotor(port3, 50);
	wait(5);
  stopMotor(port2);
  stopMotor(port3);

}
